/**
 * Plan4U - Automated Build & Synchronization Pipeline
 * 
 * Performs:
 * 1. CSS Compilation: Concatenates modular css/*.css into root style.css & www/style.css.
 * 2. Syntax Validation: Verifies that all JavaScript files compile with zero syntax errors.
 * 3. Synchronization to www/: Copies all runtime web files and assets to www/ for Capacitor and PWA.
 * 4. Cache Versioning: Automatically updates Service Worker cache timestamp.
 * 5. Capacitor Android Sync: Optionally triggers 'npx cap sync android' when --android flag is provided.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const wwwDir = path.join(rootDir, 'www');
const isAndroid = process.argv.includes('--android') || process.argv.includes('--cap');

console.log('====================================================================');
console.log('                PLAN4U BUILD & SYNC PIPELINE                        ');
console.log('====================================================================');

// 1. Compile CSS from css/ to style.css
console.log('\n[1/4] Compiling CSS from css/*.css...');
const cssDir = path.join(rootDir, 'css');
if (fs.existsSync(cssDir)) {
  const cssFiles = fs.readdirSync(cssDir)
    .filter(f => f.endsWith('.css'))
    .sort(); // Sorts 01_*, 02_*, etc. in exact numerical order

  let combinedCss = '/* Generated by scripts/build.cjs - Do not edit directly */\n';
  cssFiles.forEach(f => {
    combinedCss += fs.readFileSync(path.join(cssDir, f), 'utf8') + '\n';
  });

  fs.writeFileSync(path.join(rootDir, 'style.css'), combinedCss, 'utf8');
  console.log(` -> Compiled ${cssFiles.length} CSS modules into style.css (${combinedCss.length} bytes)`);
} else {
  console.log(' -> No css/ folder found, keeping existing style.css');
}

// 2. Validate JS syntax
console.log('\n[2/4] Validating JavaScript syntax...');
const jsFiles = [
  'modal_manager.js',
  'app.js',
  'pet_system.js',
  'stickers_system.js',
  'achievements_system.js',
  'cycle_tracker.js',
  'finance_tracker.js',
  'nutrition_tracker.js',
  'joy_tracker.js',
  'maine_quests.js',
  'maine_quests_data.js',
  'i18n.js',
  'initial_habits.js',
  'wife_habits_preset.js',
  'sw.js'
];

try {
  const checkCmd = `node -c ${jsFiles.map(f => `"${f}"`).join(' ')}`;
  execSync(checkCmd, { cwd: rootDir, stdio: 'pipe' });
  console.log(` -> Syntax check passed for all ${jsFiles.length} JS files [OK]`);
} catch (err) {
  console.error('[ERROR] JavaScript syntax validation failed:');
  console.error(err.stderr ? err.stderr.toString() : err.message);
  process.exit(1);
}

// 3. Ensure www directory structure and copy runtime files
console.log('\n[3/4] Synchronizing files to www/ directory...');
if (!fs.existsSync(wwwDir)) fs.mkdirSync(wwwDir, { recursive: true });

const filesToSync = [
  'index.html',
  'style.css',
  'sw.js',
  'manifest.json',
  'package.json',
  'favicon.png',
  'icon.png',
  'icon.svg',
  'html2canvas.min.js',
  ...jsFiles
];

filesToSync.forEach(file => {
  const src = path.join(rootDir, file);
  const dest = path.join(wwwDir, file);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, dest);
  } else {
    console.warn(`[WARN] File not found: ${file}`);
  }
});

// Recursive sync function with cleanup for assets
function copyFolderSync(from, to) {
  if (!fs.existsSync(from)) return;
  if (!fs.existsSync(to)) fs.mkdirSync(to, { recursive: true });

  // Remove files in destination that no longer exist in source
  fs.readdirSync(to).forEach(element => {
    const destPath = path.join(to, element);
    const srcPath = path.join(from, element);
    if (!fs.existsSync(srcPath)) {
      fs.rmSync(destPath, { recursive: true, force: true });
    }
  });

  // Copy files from source to destination
  fs.readdirSync(from).forEach(element => {
    const srcPath = path.join(from, element);
    const destPath = path.join(to, element);
    if (fs.lstatSync(srcPath).isDirectory()) {
      copyFolderSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  });
}

console.log(' -> Syncing assets/ directory to www/assets/...');
copyFolderSync(path.join(rootDir, 'assets'), path.join(wwwDir, 'assets'));

console.log(' -> www/ synchronized successfully [OK]');

// 4. Update Service Worker Cache Version with Timestamp
console.log('\n[4/4] Updating Service Worker cache timestamp...');
const swPath = path.join(rootDir, 'sw.js');
const wwwSwPath = path.join(wwwDir, 'sw.js');
if (fs.existsSync(swPath)) {
  let swContent = fs.readFileSync(swPath, 'utf8');
  const timestamp = new Date().toISOString().replace(/[-:T.]/g, '').slice(0, 14);
  const newCacheName = `todo-notebook-v${timestamp}`;
  swContent = swContent.replace(/const CACHE_NAME = 'todo-notebook-[^']+';/, `const CACHE_NAME = '${newCacheName}';`);
  fs.writeFileSync(swPath, swContent, 'utf8');
  fs.writeFileSync(wwwSwPath, swContent, 'utf8');
  console.log(` -> Updated SW CACHE_NAME to '${newCacheName}'`);
}

// 5. Capacitor Android Sync (Optional)
if (isAndroid) {
  console.log('\n====================================================================');
  console.log('                RUNNING CAPACITOR ANDROID SYNC                      ');
  console.log('====================================================================');
  try {
    execSync('npx cap sync android', { cwd: rootDir, stdio: 'inherit' });
    console.log('\n[OK] Capacitor Android sync completed successfully!');
  } catch (err) {
    console.error('\n[ERROR] Capacitor sync failed:', err.message);
    process.exit(1);
  }
}

console.log('\n====================================================================');
console.log('                     BUILD COMPLETED SUCCESSFULLY                   ');
console.log('====================================================================\n');
